sys:
  host: "roche-pharma-saleforce-api-sys.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
  
proc:
  host: "roche-pharma-salesforceapi-proc.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"